### ISSUE TITLE
coverage.ec not found in downloaded directory

### ISSUE THREAD

**Issue by omuomugin** [bitrise-steplib/steps-virtual-device-testing-for-android#67]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 1.1.2
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NOT APPLICABLE

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description
I need exec file from the android testing result but it turned out that no `*.exec` or `*.ec` file were included in `$VDTESTING_DOWNLOADED_FILES_DIR` directory.

as I read this discussion https://discuss.bitrise.io/t/collect-code-coverage-during-virtual-android-device-testing/3002/12 it may be worked for some time but not now.

my config is below

```
...
    - virtual-device-testing-for-android@1:
        is_skippable: true
        inputs:
        - test_devices: Pixel2,29,ja,portrait
        - directories_to_pull: "/sdcard/"
        - download_test_results: 'true'
        - environment_variables: |-
            coverage=true
            coverageFile=/sdcard/coverage.ec
        - test_type: instrumentation
...
```

when I run 

```
ls -R $VDTESTING_DOWNLOADED_FILES_DIR
```

I get 

```
Pixel2-29-ja-portrait_artifacts_5eb3c240877fe387.uid
Pixel2-29-ja-portrait_artifacts_hangouts_incoming_call.ogg
Pixel2-29-ja-portrait_artifacts_hangouts_message.ogg
Pixel2-29-ja-portrait_artifacts_sdcard_Android_data_com.google.android.youtube_cache_exo_5eb3c240877fe387.uid
Pixel2-29-ja-portrait_artifacts_sdcard_Android_media_com.google.android.talk_Notifications_hangouts_message.ogg
Pixel2-29-ja-portrait_artifacts_sdcard_Android_media_com.google.android.talk_Ringtones_hangouts_incoming_call.ogg
Pixel2-29-ja-portrait_bugreport.txt
Pixel2-29-ja-portrait_instrumentation.results
Pixel2-29-ja-portrait_logcat
Pixel2-29-ja-portrait_test_cases_0000_logcat
Pixel2-29-ja-portrait_test_cases_0001_logcat
Pixel2-29-ja-portrait_test_cases_0002_logcat
Pixel2-29-ja-portrait_test_cases_0003_logcat
Pixel2-29-ja-portrait_test_cases_0004_logcat
Pixel2-29-ja-portrait_test_result_1.xml
Pixel2-29-ja-portrait_video.mp4
```

and no `*.exec` or `*.ec` found

My question is 
- Is this a knowned issue?
- Are there any work around that I can do to get `*.exec` or `*.ec` file

### Bitrise info

- Build URL: _Please share the build URL with us._
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled:  / NO_
- Log:  NO_ 

<details>
  <pre>
 
  </pre>
</details>

### Steps to reproduce

1. set up `[BETA] Virtual Device Testing for Android` workflow
2. set below as config
```
...
    - virtual-device-testing-for-android@1:
        is_skippable: true
        inputs:
        - test_devices: Pixel2,29,ja,portrait
        - directories_to_pull: "/sdcard/"
        - download_test_results: 'true'
        - environment_variables: |-
            coverage=true
            coverageFile=/sdcard/coverage.ec
        - test_type: instrumentation
...
```
3. won't see any `*.ec` or `*.exec` file for coverage report

**Comment by bitce** [comment]
Hi @omuomugin! Sorry for the delay on your report, but thanks for raising it.

The issue is known as you suspected but the solution is not implemented yet unfortunately. We'll do our best to communicate the request and raise the priority of the problem as much as we can.

**Comment by omuomugin** [comment]
@bitce 
I got that 👍 
Waiting for the issue to be fixed! or is there anything that I can do as an individual developer? 
I mean if the missing implementation is clear, maybe I can try fixing this.

Thanks

**Comment by Roland-Bak** [comment]
Hello there @omuomugin 👋

Thank you for offering to help, it is very much appreciated. Unfortunately the developers have a lot on their hands meaning sometimes they need to prioritise in a way that some issues are attended to at later times.

But you can fork the step and create a Pull Request with a proposed solution, which is very welcome, as it would speed up the process of implementing a fix, so a win-win for everyone 🙂

**Comment by carloswabreu1** [comment]
Hello there, any update on this issue?

**Comment by Roland-Bak** [comment]
Hello @carloswabreu1 👋

I checked in with the developers to see the status of this task, and there are still discussions on how to best approach this, but the process will take more time than expected. As soon as there is an update, we'll let you know! 🙂

**Comment by carloswabreu1** [comment]
Thanks for the swift reply, @Roland-Bak. It's my understanding that this is a critical missing piece if we want to report test coverage coming from instrumented tests. Is there any other way we could be using the Sonarqube step to report test coverage that doesn't need this fix?

**Comment by ofalvai** [comment]
For those having this problem, please check if the logcat file downloaded from the test device contains an error like this:

```
06-25 02:14:42.416: E/CoverageListener(20344): Failed to generate Emma/JaCoCo coverage. 
06-25 02:14:42.416: E/CoverageListener(20344): java.lang.reflect.InvocationTargetException
06-25 02:14:42.416: E/CoverageListener(20344): 	at java.lang.reflect.Method.invoke(Native Method)
06-25 02:14:42.416: E/CoverageListener(20344): 	at androidx.test.internal.runner.listener.CoverageListener.generateCoverageReport(CoverageListener.java:101)
06-25 02:14:42.416: E/CoverageListener(20344): 	at androidx.test.internal.runner.listener.CoverageListener.instrumentationRunFinished(CoverageListener.java:70)
06-25 02:14:42.416: E/CoverageListener(20344): 	at androidx.test.internal.runner.TestExecutor.reportRunEnded(TestExecutor.java:92)
06-25 02:14:42.416: E/CoverageListener(20344): 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:65)
06-25 02:14:42.416: E/CoverageListener(20344): 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
06-25 02:14:42.416: E/CoverageListener(20344): 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
06-25 02:14:42.416: E/CoverageListener(20344): Caused by: java.io.FileNotFoundException: /sdcard/coverage.ec (Permission denied)
06-25 02:14:42.416: E/CoverageListener(20344): 	at java.io.FileOutputStream.open0(Native Method)
06-25 02:14:42.416: E/CoverageListener(20344): 	at java.io.FileOutputStream.open(FileOutputStream.java:308)
06-25 02:14:42.416: E/CoverageListener(20344): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:238)
06-25 02:14:42.416: E/CoverageListener(20344): 	at com.vladium.emma.rt.RT.dumpCoverageData(RT.java:50)
06-25 02:14:42.416: E/CoverageListener(20344): 	... 7 more
```

It's a common issue in my experience, the permission denied error means that the test application doesn't have permission to write to the `sdcard` folder. [This Stackoverflow question](https://stackoverflow.com/questions/40726208/how-to-get-code-coverage-reports-from-google-firebase-for-android-espresso-tests) has some solutions for granting that permission during the tests.

You might also run into problems with granting `android.permission.WRITE_EXTERNAL_STORAGE` because of the scoped storage enforcement in recent Android releases. Check [this issue](https://github.com/square/spoon/issues/484) for a possible solution.
